turn_on_oven:
  name: Turn on the oven
  description: Start a oven program

  fields:
    device:
      name: Oven
      description: Haier Oven
      required: true
      advanced: false
      selector:
        device:
          manufacturer: haier

    temperature:
      name: Temperature
      description: Temperature for the program
      required: true
      advanced: false
      selector:
        number:
          min: 50
          max: 240
          step: 1
          unit_of_measurement: "ºC"
          mode: slider

    preheat:
      name: Preheat
      description: Preheat the oven before start
      required: false
      advanced: false
      selector:
        boolean:

    program:
      name: Program
      description: Program mode for oven
      required: true
      selector:
        select:
          options:
            - label: Convectional
              value: 5
            - label: Taylor Bake
              value: 10
            - label: Bottom + fan
              value: 4
            - label: Botton
              value: 3
            - label: Convection + fan
              value: 6
            - label: Soft+
              value: 54
            - label: Multi-level
              value: 23

    duration:
      name: Program duration
      description: Duration, in minutes, of program
      required: false
      advanced: false
      selector:
        number:
          min: 0
          max: 600
          step: 1
          unit_of_measurement: "min"
          mode: slider

    start:
      name: Start time
      description: Time when the program will start.
      required: false
      selector:
        datetime:

    end:
      name: End time
      description: Time when the program will be finish. You need set duration too
      required: false
      selector:
        datetime:

turn_off_oven:
  name: Turn off the oven
  description: Turn off the oven
  fields:
    device:
      name: Oven
      description: Haier Oven
      required: true
      advanced: false
      selector:
        device:
          manufacturer: haier

climate_set_sleep_mode:
  name: Set climate sleep mode
  description: Set climate sleep mode
  target:
    entity:
      domain: climate
  fields:
    sleep_mode:
      name: Sleep Mode
      description: Sleep Mode value
      required: true
      advanced: false
      selector:
        boolean:

climate_set_echo_mode:
  name: Set climate echo mode
  description: Do you want your unit to do BIP at each command ?
  target:
    entity:
      domain: climate
  fields:
    echo_mode:
      name: Echo Mode
      description: True means BIP, False is silent
      required: true
      advanced: false
      selector:
        boolean:

climate_set_screen_display:
  name: Set climate screen display
  description: Do you want your unit to display current temperature all the time?
  target:
    entity:
      domain: climate
  fields:
    screen_display:
      name: Screen display
      description: True means visible, False is hidden
      required: true
      advanced: false
      selector:
        boolean:

climate_set_rapid_mode:
  name: Set climate rapid mode
  description: Activate rapid mode?
  target:
    entity:
      domain: climate
  fields:
    rapid_mode:
      name: Rapid mode
      description: True means Yes, False is no (obvious)
      required: true
      advanced: false
      selector:
        boolean:

climate_set_silent_mode:
  name: Set climate silent mode
  description: Activate silent mode?
  target:
    entity:
      domain: climate
  fields:
    silent_mode:
      name: Silent mode
      description: True means Yes, False is no (obvious)
      required: true
      advanced: false
      selector:
        boolean:

turn_off_cooler_lights:
  name: Turn off the cooler lights
  description: Turn off the cooler lights
  target:
    entity:
  fields:
    device:
      name: Wine Cooler
      description: Haier Wine Cooler
      required: true
      advanced: false
      selector:
        device:
          manufacturer: haier
          
turn_on_cooler_lights:
  name: Turn on the cooler lights
  description: Turn on the cooler lights
  target:
    entity:
  fields:
    device:
      name: Wine Cooler
      description: Haier Wine Cooler
      required: true
      advanced: false
      selector:
        device:
          manufacturer: haier
          
turn_off_purifier:
  name: Turn off the Air Purifier
  description: Turn off Air Purifier
  fields:
    device:
      name: Purifier
      description: Hoover Air Purifier
      required: true
      advanced: false
      selector:
        device:
          manufacturer: 
          
turn_on_purifier:
  name: Turn on the Air Purifier
  description: Turn on Air Purifier
  fields:
    device:
      name: Purifier
      description: Hoover Air Purifier
      required: true
      advanced: false
      selector:
        device:
          manufacturer: hoover